packages:
  - 'packages/**'
  - 'tools/*'

prefer-workspace-packages: true
save-workspace-protocol: true

hoist-pattern:
  - '*eslint*'
  - '*prettier*'
  - '*typescript*'
  - 'express'
  - 'supertest'
  - '@nestjs/*'
  - 'rxjs'

link-workspace-packages: true

