packages:
  - 'packages/*'
  - 'tools/*'

prefer-workspace-packages: true
save-workspace-protocol: true

hoist-pattern:
  - '*eslint*'
  - '*prettier*'
  - '*typescript*'
  - 'express'
  - 'supertest'

link-workspace-packages: true

